### ISSUE TITLE
tfbuild help command requires valid configurations

### ISSUE THREAD

**Issue by acelinkio** [mpearson117/tfbuild#1]
**Summary**
tfbuild help is not able to run without project configuration.

**Details** 
tfbuild` requires that a git project be initialized 
```
$ tfbuild help
  You are not executing TFBUILD from a git repository !
  Please ensure execution from a resurce directory inside a git repository !
```
and also required files exist
```
$ tfbuild help
  No Common Wrapper Shell File available ! Please create:
  /mnt/c/Users/acelinkit/source/repos/mytestlab/common/environments/env_main.hcl
  and add configuration content if necessary !
```
tfbuild should not encounter errors when ran executed without parameters and default to help action
```
$ tfbuild
Traceback (most recent call last):
  File "/home/acelinkit/python_env/ansible5/bin/tfbuild", line 8, in <module>
    sys.exit(main())
  File "/home/acelinkit/python_env/tfbuild/lib/python3.8/site-packages/tfbuild/cli.py", line 12, in main
    if "-" in sys.argv[1]:
IndexError: list index out of range
```

**Comment by mpearson117** [comment]
All commands are meant to be issued from a structured repository only and all requirements need to be satisfied.
Will handle the lack of a command to TFBuild by pointing it to help and subsequently to documentation.

**Comment by mpearson117** [comment]
Issues handled in version 1.2.0

**Comment by mpearson117** [comment]
Issue handled in release v1.2.1
