### ISSUE TITLE
tfbuild validate

### ISSUE THREAD

**Issue by acelinkio** [mpearson117/tfbuild#2]
tfbuild has no action for running terraform validate and creates an odd usage pattern of switching between terraform and tfbuild command.

```
tfbuild init
terraform validate
tfbuild replan
```

**Comment by mpearson117** [comment]
As per the app documentation, only a set of opinionated commands are supported.
For validation please use the "plan" command.
That being said, there should be no issues implementing validation.
Stay tuned ...

**Comment by mpearson117** [comment]
Validate command introduced in version 1.2.0
